name: Learning Perspective
favicon: null
layout_spectrum: 0.5103788480628282
typography_spectrum: 0.16944254306145012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.20236971089616418
  lightness: 0.809182739816606
  saturation: 0.0853124491404742
  rhythmicContrast: 0.12978936778381467
purpose: []
